version: '3.4'

services:
  catalogdb:
   container_name: catalogdb
   restart: always
   volumes: 
   - C:\Users\anirudh.singh.bharti\OneDrive - Accenture\Desktop\mongo:/data/db
   ports:
   - "27017:27017"

  basketdb:
   container_name: basketdb
   restart: always    
   ports:
   - "6379:6379"

  discountdb:
   container_name: discountdb
   environment:
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=admin1234
   - POSTGRES_DB=DiscountDb
   restart: always
   ports:
   - "5432:5432"
   volumes:
   -  C:\Users\anirudh.singh.bharti\OneDrive - Accenture\Desktop\postgres_data:/var/lib/postgresql/data/
   
  catalog.api:
   container_name: catalog.api
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   depends_on:
   - catalogdb  
   ports:
   - "5000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - basketdb
    ports:
     - "5001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - C:\Users\anirudh.singh.bharti\OneDrive - Accenture\Desktop\pgadmin_data:/root/.pgadmin

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discountdb
    ports:
      - "5002:80"

  ocelotapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
    ports:
      - "5010:80"
